app/demos/forms.py
from flask_wtf import FlaskForm
from govuk_frontend_wtf.wtforms_widgets import (
    GovCharacterCount,
    GovCheckboxesInput,
    GovCheckboxInput,
    GovDateInput,
    GovFileInput,
    GovPasswordInput,
    GovRadioInput,
    GovSelect,
    GovSubmitInput,
    GovTextArea,
    GovTextInput,
)
from wtforms.fields import (
    BooleanField,
    DateField,
    DateTimeField,
    DecimalField,
    FileField,
    FloatField,
    IntegerField,
    MultipleFileField,
    PasswordField,
    RadioField,
    SelectField,
    SelectMultipleField,
    StringField,
    SubmitField,
    TextAreaField,
)
from wtforms.validators import Email, EqualTo, InputRequired, Length, Optional, Regexp, ValidationError

from app.demos.custom_validators import RequiredIf


class BankDetailsForm(FlaskForm):
    name_on_the_account = StringField(
        "Name on the account",
        widget=GovTextInput(),
        validators=[InputRequired(message="Enter the name on the account")],
    )
    sort_code = StringField(
        "Sort code",
        widget=GovTextInput(),
        validators=[
            InputRequired(message="Enter a sort code"),
            Regexp(regex=r"\d{6}", message="Enter a valid sort code like 309430"),
        ],
        description="Must be 6 digits long",
    )
    account_number = StringField(
        "Account number",
        widget=GovTextInput(),
        validators=[
            InputRequired(message="Enter an account number"),
            Regexp(regex=r"\d{6,8}", message="Enter a valid account number like 00733445"),
            Length(min=6, max=8, message="Account number must be between 6 and 8 digits"),
        ],
        description="Must be between 6 and 8 digits long",
    )
    roll_number = StringField(
        "Building society roll number (if you have one)",
        widget=GovTextInput(),
        validators=[
            Optional(),
            Length(
                min=1,
                max=18,
                message="Building society roll number must be between 1 and 18 characters",
            ),
            Regexp(
                regex=r"[a-zA-Z0-9- /.]*$",
                message="Building society roll number must only include letters a to z, numbers, hyphens, spaces, forward slashes and full stops",
            ),
        ],
        description="You can find it on your card, statement or passbook",
    )
    submit = SubmitField("Continue", widget=GovSubmitInput())


class CreateAccountForm(FlaskForm):
    first_name = StringField(
        "First name",
        widget=GovTextInput(),
        validators=[InputRequired(message="Enter your first name")],
    )
    last_name = StringField(
        "Last name",
        widget=GovTextInput(),
        validators=[InputRequired(message="Enter your last name")],
    )
    date_of_birth = DateField(
        "Date of birth",
        widget=GovDateInput(),
        format="%d %m %Y",
        validators=[InputRequired(message="Enter your date of birth")],
        description="For example, 31 3 1980",
    )
    national_insurance_number = StringField(
        "National Insurance number",
        widget=GovTextInput(),
        validators=[
            InputRequired(message="Enter a National Insurance number"),
            Length(
                max=13,
                message="National Insurance number must be 13 characters or fewer",
            ),
            Regexp(
                regex=r"^[a-zA-Z]{2}\d{6}[aAbBcCdD]$",
                message="Enter a National Insurance number in the correct format",
            ),
        ],
        description="It’s on your National Insurance card, benefit letter, payslip or P60. For example, ‘QQ 12 34 56 C’.",
    )
    email_address = StringField(
        "Email address",
        widget=GovTextInput(),
        validators=[
            InputRequired(message="Enter an email address"),
            Length(max=256, message="Email address must be 256 characters or fewer"),
            Email(message="Enter an email address in the correct format, like name@example.com"),
        ],
        description="You'll need this email address to sign in to your account",
    )
    telephone_number = StringField(
        "UK telephone number",
        widget=GovTextInput(),
        validators=[
            InputRequired(message="Enter a UK telephone number"),
            Regexp(
                regex=r"[\d \+]",
                message="Enter a telephone number, like 01632 960 001, 07700 900 982 or +44 0808 157 0192",
            ),
        ],
    )
    password = PasswordField(
        "Create a password",
        widget=GovPasswordInput(),
        validators=[
            InputRequired(message="Enter a password"),
            Length(min=8, message="Password must be at least 8 characters"),
        ],
        description="Must be at least 8 characters",
    )
    confirm_password = PasswordField(
        "Confirm password",
        widget=GovPasswordInput(),
        validators=[
            InputRequired(message="Confirm your password"),
            EqualTo("password", message="Passwords must match"),
        ],
    )
    terms_and_conditions = BooleanField(
        "I agree to the terms and conditions",
        widget=GovCheckboxInput(),
        validators=[InputRequired(message="Select to confirm you agree with the terms and conditions")],
    )
    submit = SubmitField("Create account", widget=GovSubmitInput())


class KitchenSinkForm(FlaskForm):
    string_field = StringField(
        "StringField",
        widget=GovTextInput(),
        validators=[InputRequired(message="StringField is required")],
        description="Hint text: WTForm StringField rendered using a GovTextInput widget.",
    )

    email_field = StringField(
        "EmailField",
        widget=GovTextInput(),
        validators=[InputRequired(message="EmailField is required"), Email()],
        description="Hint text: WTForm StringField rendered using a GovTextInput widget.",
    )

    float_field = FloatField(
        "FloatField",
        widget=GovTextInput(),
        validators=[InputRequired(message="FloatField is required")],
        description="Hint text: WTForm FloatField rendered using a GovTextInput widget.",
    )

    integer_field = IntegerField(
        "IntegerField",
        widget=GovTextInput(),
        validators=[InputRequired(message="IntegerField is required")],
        description="Hint text: WTForm IntegerField rendered using a GovTextInput widget.",
    )

    decimal_field = DecimalField(
        "DecimalField",
        widget=GovTextInput(),
        validators=[InputRequired(message="DecimalField is required")],
        description="Hint text: WTForm DecimalField rendered using a GovTextInput widget.",
    )

    textarea_field = TextAreaField(
        "TextAreaField",
        widget=GovTextArea(),
        validators=[InputRequired(message="TextAreaField is required")],
        description="Hint text: WTForm TextAreaField rendered using a GovTextArea widget.",
    )

    charactercount_field = TextAreaField(
        "CharacterCountField",
        widget=GovCharacterCount(),
        validators=[
            InputRequired(message="CharacterCountField is required"),
            Length(max=200, message="CharacterCountField must be 200 characters or fewer "),
        ],
        description="Hint text: WTForm TextAreaField rendered using a GovCharacterCount widget.",
    )

    boolean_field = BooleanField(
        "BooleanField",
        widget=GovCheckboxInput(),
        validators=[InputRequired(message="Please tick the box")],
        description="Hint text: WTForm BooleanField rendered using a GovCheckboxInput widget.",
    )

    select_field = SelectField(
        "SelectField",
        widget=GovSelect(),
        validators=[InputRequired(message="Please select an option")],
        choices=[
            ("", "Please select"),
            ("one", "One"),
            ("two", "Two"),
            ("three", "Three"),
        ],
        default="",
        description="Hint text: WTForm SelectField rendered using a GovSelect widget.",
    )

    select_multiple_field = SelectMultipleField(
        "SelectMultipleField",
        widget=GovCheckboxesInput(),
        validators=[InputRequired(message="Please select an option")],
        choices=[("one", "One"), ("two", "Two"), ("three", "Three")],
        description="Hint text: WTForm SelectMultipleField rendered using a GovCheckboxesInput widget.",
    )

    radio_field = RadioField(
        "RadioField",
        widget=GovRadioInput(),
        validators=[InputRequired(message="Please select an option")],
        choices=[("one", "One"), ("two", "Two"), ("three", "Three")],
        description="Hint text: WTForm RadioField rendered using a GovRadioInput widget.",
    )

    file_field = FileField(
        "FileField",
        widget=GovFileInput(),
        validators=[InputRequired(message="Please upload a file")],
        description="Hint text: WTForm FileField rendered using a GovFileInput widget.",
    )

    multiple_file_field = MultipleFileField(
        "MultipleFileField",
        widget=GovFileInput(multiple=True),
        validators=[InputRequired(message="Please upload a file")],
        description="Hint text: WTForm MultipleFileField rendered using a MultipleFileField widget.",
    )

    password_field = PasswordField(
        "PasswordField",
        widget=GovPasswordInput(),
        validators=[
            InputRequired("Password is required"),
            EqualTo(
                "password_retype_field",
                message="Please ensure both password fields match",
            ),
        ],
        description="Hint text: WTForm PasswordField rendered using a GovPasswordInput widget.",
    )

    date_field = DateField(
        "DateField",
        widget=GovDateInput(),
        validators=[InputRequired(message="DateField is required")],
        description="Hint text: WTForm DateField rendered using a GovDateInput widget.",
    )

app/demos/__init__.py
from flask import Blueprint

bp = Blueprint("demos", __name__, template_folder="../templates/demos")

from app.demos import routes  # noqa: E402,F401

app/demos/routes.py
import json
import os

from flask import flash, redirect, render_template, url_for
from werkzeug.exceptions import NotFound

from app.demos import bp
from app.demos.forms import AutocompleteForm, BankDetailsForm, ConditionalRevealForm, CreateAccountForm, KitchenSinkForm


@bp.route("/components", methods=["GET"])
def components():
    components = os.listdir("govuk_components")
    components.sort()

    return render_template("components.html", components=components)


@bp.route("/components/<string:component>", methods=["GET"])
def component(component):
    try:
        with open("govuk_components/{}/fixtures.json".format(component)) as json_file:
            fixtures = json.load(json_file)
    except FileNotFoundError:
        raise NotFound

    return render_template("component.html", fixtures=fixtures)


@bp.route("/forms", methods=["GET"])
def forms():
    return render_template("forms.html")


@bp.route("/forms/bank-details", methods=["GET", "POST"])
def bank_details():
    form = BankDetailsForm()
    if form.validate_on_submit():
        flash("Demo form successfully submitted", "success")
        return redirect(url_for("demos.forms"))
    return render_template("bank_details.html", form=form)


@bp.route("/forms/create-account", methods=["GET", "POST"])
def create_account():
    form = CreateAccountForm()
    if form.validate_on_submit():
        flash("Demo form successfully submitted", "success")
        return redirect(url_for("demos.forms"))
    return render_template("create_account.html", form=form)


@bp.route("/forms/kitchen-sink", methods=["GET", "POST"])
def kitchen_sink():
    form = KitchenSinkForm()
    if form.validate_on_submit():
        flash("Demo form successfully submitted", "success")
        return redirect(url_for("demos.forms"))
    return render_template("kitchen_sink.html", form=form)


@bp.route("/forms/conditional-reveal", methods=["GET", "POST"])
def conditional_reveal():
    form = ConditionalRevealForm()
    if form.validate_on_submit():
        flash("Demo form successfully submitted", "success")
        return redirect(url_for("demos.forms"))
    return render_template("conditional_reveal.html", form=form)


@bp.route("/forms/autocomplete", methods=["GET", "POST"])
def autocomplete():
    form = AutocompleteForm()
    if form.validate_on_submit():
        flash("Demo form successfully submitted", "success")
        return redirect(url_for("demos.forms"))
    return render_template("autocomplete.html", form=form)

app/templates/demos/autocomplete.html
{% extends "base.html" %}

{%- from 'govuk_frontend_jinja/components/breadcrumbs/macro.html' import govukBreadcrumbs -%}

{% block pageTitle %}{%- if form.errors %}Error: {% endif -%}Autocomplete – GOV.UK{% endblock %}

{% block beforeContent %}
  {{ super() }}
  {{ govukBreadcrumbs({
    'collapseOnMobile': True,
    'items': [
        {
            'text': "Home",
            'href': url_for('main.index')
        },
        {
            'text': "Forms",
            'href': url_for('demos.forms')
        },
        {
            'text': "Autocomplete"
        }
    ]
  }) }}
{% endblock %}

{% block content %}
<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    {{ super() }}
    <span class="govuk-caption-xl">Demo form</span>
    <h1 class="govuk-heading-xl">Autocomplete</h1>

    <form action="" method="post" novalidate>
      {{ form.csrf_token }}

      {{ form.country(params={
        'spellcheck': true,
        'attributes': {
            'list': "countries"
        },
      }) }}

      <datalist id="countries">
        {% for country in form.countries %}
          <option value="{{country}}">
        {% endfor %}
      </datalist>

      {{ form.submit }}
    </form>
  </div>
</div>
{% endblock %}

app/templates/demos/bank_details.html
{% extends "base.html" %}

{%- from 'govuk_frontend_jinja/components/breadcrumbs/macro.html' import govukBreadcrumbs -%}

{% block pageTitle %}{%- if form.errors %}Error: {% endif -%}Bank details – GOV.UK{% endblock %}

{% block beforeContent %}
  {{ super() }}
  {{ govukBreadcrumbs({
    'collapseOnMobile': True,
    'items': [
        {
            'text': "Home",
            'href': url_for('main.index')
        },
        {
            'text': "Forms",
            'href': url_for('demos.forms')
        },
        {
            'text': "Bank details"
        }
    ]
  }) }}
{% endblock %}

{% block content %}
<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    {{ super() }}
    <span class="govuk-caption-xl">Demo form</span>
    <h1 class="govuk-heading-xl">Bank or building society account details</h1>

    <form action="" method="post" novalidate>
      {{ form.csrf_token }}

      {{ form.name_on_the_account(params={
        'spellcheck': false
      }) }}

      {{ form.sort_code(params={
        'classes': 'govuk-input--width-5',
        'inputmode': 'numeric',
        'pattern': '[0-9]*',
        'spellcheck': false
      }) }}

      {{ form.account_number(params={
        'classes': 'govuk-input--width-10',
        'inputmode': 'numeric',
        'pattern': '[0-9]*',
        'spellcheck': false
      }) }}

      {{ form.roll_number(params={
        'classes': 'govuk-input--width-10',
        'spellcheck': false
      }) }}

      {{ form.submit }}
    </form>
  </div>
</div>
{% endblock %}

app/templates/demos/component.html
{% extends "base.html" %}

{%- from 'govuk_frontend_jinja/components/accordion/macro.html' import govukAccordion -%}
{%- from 'govuk_frontend_jinja/components/back-link/macro.html' import govukBackLink -%}
{%- from 'govuk_frontend_jinja/components/breadcrumbs/macro.html' import govukBreadcrumbs -%}
{%- from 'govuk_frontend_jinja/components/button/macro.html' import govukButton -%}
{%- from 'govuk_frontend_jinja/components/character-count/macro.html' import govukCharacterCount -%}
{%- from 'govuk_frontend_jinja/components/checkboxes/macro.html' import govukCheckboxes -%}
{%- from 'govuk_frontend_jinja/components/cookie-banner/macro.html' import govukCookieBanner -%}
{%- from 'govuk_frontend_jinja/components/date-input/macro.html' import govukDateInput -%}
{%- from 'govuk_frontend_jinja/components/details/macro.html' import govukDetails -%}
{%- from 'govuk_frontend_jinja/components/error-message/macro.html' import govukErrorMessage -%}
{%- from 'govuk_frontend_jinja/components/error-summary/macro.html' import govukErrorSummary -%}
{%- from 'govuk_frontend_jinja/components/exit-this-page/macro.html' import govukExitThisPage -%}
{%- from 'govuk_frontend_jinja/components/fieldset/macro.html' import govukFieldset -%}
{%- from 'govuk_frontend_jinja/components/file-upload/macro.html' import govukFileUpload -%}
{%- from 'govuk_frontend_jinja/components/footer/macro.html' import govukFooter -%}
{%- from 'govuk_frontend_jinja/components/header/macro.html' import govukHeader -%}
{%- from 'govuk_frontend_jinja/components/hint/macro.html' import govukHint -%}
{%- from 'govuk_frontend_jinja/components/input/macro.html' import govukInput -%}
{%- from 'govuk_frontend_jinja/components/inset-text/macro.html' import govukInsetText -%}
{%- from 'govuk_frontend_jinja/components/label/macro.html' import govukLabel -%}
{%- from 'govuk_frontend_jinja/components/notification-banner/macro.html' import govukNotificationBanner -%}
{%- from 'govuk_frontend_jinja/components/pagination/macro.html' import govukPagination -%}
{%- from 'govuk_frontend_jinja/components/panel/macro.html' import govukPanel -%}
{%- from 'govuk_frontend_jinja/components/phase-banner/macro.html' import govukPhaseBanner -%}
{%- from 'govuk_frontend_jinja/components/radios/macro.html' import govukRadios -%}
{%- from 'govuk_frontend_jinja/components/select/macro.html' import govukSelect -%}
{%- from 'govuk_frontend_jinja/components/skip-link/macro.html' import govukSkipLink -%}
{%- from 'govuk_frontend_jinja/components/summary-list/macro.html' import govukSummaryList -%}
{%- from 'govuk_frontend_jinja/components/table/macro.html' import govukTable -%}
{%- from 'govuk_frontend_jinja/components/tabs/macro.html' import govukTabs -%}
{%- from 'govuk_frontend_jinja/components/tag/macro.html' import govukTag -%}
{%- from 'govuk_frontend_jinja/components/textarea/macro.html' import govukTextarea -%}
{%- from 'govuk_frontend_jinja/components/warning-text/macro.html' import govukWarningText -%}

{% block pageTitle %}{{fixtures.component | replace("-", " ") | capitalize}} – GOV.UK{% endblock %}

{% block beforeContent %}
  {{ super() }}
  {{ govukBreadcrumbs({
    'collapseOnMobile': True,
    'items': [
        {
            'text': "Home",
            'href': url_for('main.index')
        },
        {
            'text': "Components",
            'href': url_for('demos.components')
        },
        {
            'text': fixtures.component | replace("-", " ") | capitalize
        }
    ]
  }) }}
{% endblock %}

{% block content %}
  <span class="govuk-caption-xl">Components</span>
  <h1 class="govuk-heading-xl">{{fixtures.component | replace("-", " ") | capitalize}}</h1>

  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
      <p class="govuk-body">Examples:</p>
      <ul class="govuk-list govuk-list--bullet">
        {% for fixture in fixtures.fixtures if fixture.hidden == False %}
          <li>
            <a class="govuk-link" href="#{{fixture.name | replace(' ', '-')}}">{{fixture.name | capitalize}}</a>
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>
  <hr class="govuk-section-break govuk-section-break--m govuk-section-break--visible">
  {% for fixture in fixtures.fixtures if fixture.hidden == False %}
    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">
            <h2 id="{{fixture.name | replace(' ', '-')}}" class="govuk-heading-l">{{fixture.name | capitalize}}</h2>
            {% if fixtures.component == 'accordion' %}
              {{ govukAccordion(fixture.options) }}
            {% elif fixtures.component == 'back-link' %}
              {{ govukBackLink(fixture.options)}}
            {% elif fixtures.component == 'breadcrumbs' %}
              {{ govukBreadcrumbs(fixture.options)}}
            {% elif fixtures.component == 'button' %}
              {{ govukButton(fixture.options)}}
            {% elif fixtures.component == 'character-count' %}
              {{ govukCharacterCount(fixture.options)}}
            {% elif fixtures.component == 'checkboxes' %}
              {{ govukCheckboxes(fixture.options)}}
            {% elif fixtures.component == 'cookie-banner' %}
              {{ govukCookieBanner(fixture.options)}}
            {% elif fixtures.component == 'date-input' %}
              {{ govukDateInput(fixture.options)}}
            {% elif fixtures.component == 'details' %}
              {{ govukDetails(fixture.options)}}
            {% elif fixtures.component == 'error-message' %}
              {{ govukErrorMessage(fixture.options)}}
            {% elif fixtures.component == 'error-summary' %}
              {{ govukErrorSummary(fixture.options)}}
            {% elif fixtures.component == 'exit-this-page' %}
              {{ govukExitThisPage(fixture.options)}}
            {% elif fixtures.component == 'fieldset' %}
              {{ govukFieldset(fixture.options)}}
            {% elif fixtures.component == 'file-upload' %}
              {{ govukFileUpload(fixture.options)}}
            {% elif fixtures.component == 'footer' %}
              {{ govukFooter(fixture.options)}}
            {% elif fixtures.component == 'header' %}
              {{ govukHeader(fixture.options)}}
            {% elif fixtures.component == 'hint' %}
              {{ govukHint(fixture.options)}}
            {% elif fixtures.component == 'input' %}
              {{ govukInput(fixture.options)}}
            {% elif fixtures.component == 'inset-text' %}
              {{ govukInsetText(fixture.options)}}
            {% elif fixtures.component == 'label' %}
              {{ govukLabel(fixture.options)}}
            {% elif fixtures.component == 'notification-banner' %}
              {{ govukNotificationBanner(fixture.options)}}
            {% elif fixtures.component == 'pagination' %}
              {{ govukPagination(fixture.options)}}
            {% elif fixtures.component == 'panel' %}
              {{ govukPanel(fixture.options)}}
            {% elif fixtures.component == 'phase-banner' %}
              {{ govukPhaseBanner(fixture.options)}}
            {% elif fixtures.component == 'radios' %}
              {{ govukRadios(fixture.options)}}
            {% elif fixtures.component == 'select' %}
              {{ govukSelect(fixture.options)}}
            {% elif fixtures.component == 'skip-link' %}
              {{ govukSkipLink(fixture.options)}}
            {% elif fixtures.component == 'summary-list' %}
              {{ govukSummaryList(fixture.options)}}
            {% elif fixtures.component == 'table' %}
              {{ govukTable(fixture.options)}}
            {% elif fixtures.component == 'tabs' %}
              {{ govukTabs(fixture.options)}}
            {% elif fixtures.component == 'tag' %}
              {{ govukTag(fixture.options)}}
            {% elif fixtures.component == 'textarea' %}
              {{ govukTextarea(fixture.options)}}
            {% elif fixtures.component == 'warning-text' %}
              {{ govukWarningText(fixture.options)}}
            {% endif %}

            {{ govukDetails({
              'summaryText': "Jinja macro options",
              'text': fixture.options
            })}}

            {{ govukDetails({
              'summaryText': "HTML",
              'text': fixture.html
            })}}
        </div>
    </div>
  {% endfor %}
{% endblock %}

app/templates/demos/components.html
{% extends "base.html" %}

{%- from 'govuk_frontend_jinja/components/breadcrumbs/macro.html' import govukBreadcrumbs -%}

{% block beforeContent %}
    {{ super() }}
    {{ govukBreadcrumbs({
        'collapseOnMobile': True,
        'items': [
            {
                'text': "Home",
                'href': url_for('main.index')
            },
            {
                'text': "Components"
            }
        ]
    }) }}
{% endblock %}

{% block content %}
<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <span class="govuk-caption-xl">Demo</span>
    <h1 class="govuk-heading-l">Components</h1>
    <ul class="govuk-list govuk-list--bullet">
      {% for component in components %}
      <li>
        <a class="govuk-link" href="{{ url_for('demos.component', component=component) }}">{{component | replace("-", " ") | capitalize}}</a>
      </li>
      {% endfor %}
    </ul>
  </div>
</div>
{% endblock %}

app/templates/demos/conditional_reveal.html
{% extends "base.html" %}

{%- from 'govuk_frontend_jinja/components/breadcrumbs/macro.html' import govukBreadcrumbs -%}

{% block pageTitle %}{%- if form.errors %}Error: {% endif -%}Conditionally revealed inputs – GOV.UK{% endblock %}

{% block beforeContent %}
  {{ super() }}
  {{ govukBreadcrumbs({
    'collapseOnMobile': True,
    'items': [
        {
            'text': "Home",
            'href': url_for('main.index')
        },
        {
            'text': "Forms",
            'href': url_for('demos.forms')
        },
        {
            'text': "Conditional reveal"
        }
    ]
  }) }}
{% endblock %}

{% block content %}
<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    {{ super() }}
    <span class="govuk-caption-xl">Demo form</span>
    <h1 class="govuk-heading-xl">Conditionally revealed inputs</h1>

    <form action="" method="post" novalidate>
      {{ form.csrf_token }}

      <!-- Grab html for conditional fields -->
      {% set emailHtml %}
        {{ form.contact_by_email(params={
          'type': 'email',
          'autocomplete': 'email',
          'spellcheck': false,
          'classes': 'govuk-!-width-one-third'
        }) }}
      {% endset %}

      {% set phoneHtml %}
        {{ form.contact_by_phone(params={
          'type': 'tel',
          'autocomplete': 'tel',
          'classes': 'govuk-!-width-one-third'
        }) }}
      {% endset %}

      {% set textHtml %}
        {{ form.contact_by_text(params={
          'type': 'tel',
          'autocomplete': 'tel',
          'classes': 'govuk-!-width-one-third'
        }) }}
      {% endset %}

      <!--
      Render the radio buttons
      The conditional field html is passed in via the params argument which is 
      deep merged into the params generated by govuk-frontend-wtf.
      
      This is the same structure that is documented on the govuk design system.
      https://design-system.service.gov.uk/components/radios/#conditionally-revealing-a-related-question
      
      The field definition in ConditionalRevealForm has three options.
      Therefore we have an array of three items here to match.
      -->
      {{ form.contact(params={
        'items': [
          {
            'conditional': {
              'html': emailHtml
            }
          },
          {
            'conditional': {
              'html': phoneHtml
            }
          },
          {
            'conditional': {
              'html': textHtml
            }
          }
        ]
      }) }}      

      {{ form.submit }}
    </form>
  </div>
</div>
{% endblock %}

app/templates/demos/forms.html
{% extends "base.html" %}

{%- from 'govuk_frontend_jinja/components/breadcrumbs/macro.html' import govukBreadcrumbs -%}

{% block beforeContent %}
    {{ super() }}

    {{ govukBreadcrumbs({
        'collapseOnMobile': True,
        'items': [
            {
                'text': "Home",
                'href': url_for('main.index')
            },
            {
                'text': "Forms"
            }
        ]
    }) }}
{% endblock %}

{% block content %}
<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    {{ super() }}
    <span class="govuk-caption-xl">Demo</span>
    <h1 class="govuk-heading-l">Forms</h1>
    <ul class="govuk-list govuk-list--bullet">
      <li><a class="govuk-link" href="{{ url_for('demos.autocomplete') }}">Autocomplete</a></li>
      <li><a class="govuk-link" href="{{ url_for('demos.bank_details') }}">Bank details</a></li>
      <li><a class="govuk-link" href="{{ url_for('demos.conditional_reveal') }}">Conditional reveal</a></li>
      <li><a class="govuk-link" href="{{ url_for('demos.create_account') }}">Create account</a></li>
      <li><a class="govuk-link" href="{{ url_for('demos.kitchen_sink') }}">Kitchen sink</a></li>
    </ul>
  </div>
</div>
{% endblock %}